services:
  - type: web
    plan: free
    name: chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/badmunda011/ChatBot
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: MONGO_URL
        sync: false
      - key: OWNER_ID
        sync: false
